# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Debug ${tag_name}"
        env:
          tag_name: ${{github.event.release.tag_name}}
      - name: Setup env vars
        run: echo "PACKAGE_VERSION=${TAG_NAME#v}" >> $GITHUB_ENV
        env:
          TAG_NAME: ${{github.event.release.tag_name}}
      - run: echo "Releasing as version $PACKAGE_VERSION"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: "sed -i \"s/\\\"version\\\": .*,/\\\"version\\\": \\\"${{env.PACKAGE_VERSION}}\\\",/g\" \"package.json\""
      - run: yarn install --frozen-lockfile
      # - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
